In [10]:
import numpy as np

a = np.array([6,4,4,4,6,8])

In [11]:
a

array([6, 4, 4, 4, 6, 8])

In [12]:
from scipy import signal

In [33]:
signal.convolve(a, np.array([1,1]), 'same')/2

array([3., 5., 4., 4., 5., 7.])

In [34]:
signal.medfilt(a, 3)

array([4., 4., 4., 4., 6., 6.])